[tool.black]
line-length = 130
target-version = ['py310']
skip-string-normalization = true
include = '\.pyi?$'

[tool.ruff]
line-length = 130
fix = true
select = ["ALL"]
ignore = ["ANN", "D", "COM", "PLR0913", "E501","S311" ,"ERA001"]
src = ["src"]